"""Chat JSON export parser.

Parses WeFlow JSON and the JSON generated by wechat-decrypt into ChatMessage
objects matching the frontend contract.
"""

from __future__ import annotations

import html
import json
import re
from datetime import datetime

from models import ChatMessage

_URL_RE = re.compile(r"https?://[^\s\"'<>]+")


def _as_text(value: object) -> str:
    return value.strip() if isinstance(value, str) else ""


def _clean_url(value: str) -> str:
    return html.unescape(value).rstrip(".,;)")


def _direct_url(value: object) -> str:
    text = _clean_url(_as_text(value))
    return text if text.startswith(("http://", "https://")) else ""


def _extract_first_url(*values: object) -> str:
    for value in values:
        match = _URL_RE.search(_as_text(value))
        if match:
            return _clean_url(match.group(0))
    return ""


def _detect_weflow_message_type(local_type: int) -> str:
    type_map = {
        1: "text",
        3: "image",
        34: "file",
        43: "file",
        47: "emoji",
        49: "file",
        50: "unknown",
        10000: "system",
    }
    return type_map.get(local_type, "text")


def parse_weflow_json(text: str) -> list[ChatMessage]:
    """Parse WeFlow JSON export into structured ChatMessage list."""
    data = json.loads(text)
    raw_msgs = data.get("messages", []) if isinstance(data, dict) else []

    messages: list[ChatMessage] = []
    for i, m in enumerate(raw_msgs):
        local_type = int(m.get("localType", 1) or 1)
        msg_type = _detect_weflow_message_type(local_type)

        content = str(m.get("content", "") or "")
        meta = None
        if local_type == 47:
            sticker_md5 = m.get("emojiMd5", "")
            sticker_url = (
                _direct_url(m.get("emojiCdnUrl"))
                or _direct_url(m.get("source"))
                or _extract_first_url(m.get("content"), m.get("source"))
            )
            sticker_local_path = _as_text(m.get("emojiLocalPath"))
            label = m.get("emojiCaption", "") or "[表情包]"
            content = label
            meta = {"url": sticker_url, "caption": label, "md5": sticker_md5}
            if sticker_local_path:
                meta["local_path"] = sticker_local_path

        messages.append(ChatMessage(
            msg_id=str(m.get("localId", i)),
            sender=str(m.get("senderDisplayName", "") or m.get("senderUsername", "") or "未知"),
            ts=str(m.get("formattedTime", "")).replace(" ", "T") if m.get("formattedTime") else "",
            type=msg_type,
            content=content,
            meta=meta,
        ))
    return messages


def _wechat_type(raw_type: object, content: str) -> str:
    kind = str(raw_type or "text").strip().lower()
    if kind in ("text", ""):
        return "text"
    if kind == "image":
        return "image"
    if kind in ("sticker", "emoji"):
        return "emoji"
    if kind == "transfer":
        return "transfer"
    if kind in ("red_packet", "hongbao"):
        return "red_packet"
    if kind in ("system", "recall"):
        return "system"
    if kind == "link_or_file":
        if content.startswith("[链接]") or content.startswith("[小程序]") or _URL_RE.search(content):
            return "link"
        return "file"
    if kind in ("voice", "video", "contact_card", "location", "call"):
        return "file"
    return "unknown"


def _timestamp_to_iso(value: object) -> str:
    try:
        return datetime.fromtimestamp(int(value)).isoformat()
    except (TypeError, ValueError, OSError, OverflowError):
        return ""


def parse_wechat_decrypt_json(text: str) -> list[ChatMessage]:
    """Parse JSON exported by the wechat-decrypt reference project."""
    data = json.loads(text)
    raw_msgs = data.get("messages", []) if isinstance(data, dict) else []

    messages: list[ChatMessage] = []
    for i, m in enumerate(raw_msgs):
        raw_type = m.get("type", "text")
        content = str(m.get("transcription") or m.get("content") or "")
        msg_type = _wechat_type(raw_type, content)
        meta: dict[str, str | int | bool] = {}

        if raw_type:
            meta["source_type"] = str(raw_type)
        if m.get("sender") == "me":
            meta["from_me"] = True
        if isinstance(m.get("transfer"), dict):
            transfer = m["transfer"]
            for key in ("direction", "fee_desc", "pay_memo"):
                if transfer.get(key):
                    meta[f"transfer_{key}"] = str(transfer[key])

        sender = str(m.get("sender") or "")
        if sender == "me":
            sender = "我"
        if not sender and msg_type == "system":
            sender = "系统"

        messages.append(ChatMessage(
            msg_id=str(m.get("local_id", i)),
            sender=sender or "未知",
            ts=_timestamp_to_iso(m.get("timestamp")),
            type=msg_type,
            content=content,
            meta=meta or None,
        ))
    return messages


def parse_and_validate(text: str) -> list[ChatMessage]:
    """Validate and parse supported chat JSON text."""
    try:
        data = json.loads(text.strip())
    except json.JSONDecodeError as exc:
        raise ValueError("JSON 格式解析失败，请上传 WeFlow 或微信解密导出的 JSON 文件。") from exc

    raw_msgs = data.get("messages", []) if isinstance(data, dict) else []
    if raw_msgs and isinstance(raw_msgs[0], dict) and "timestamp" in raw_msgs[0]:
        messages = parse_wechat_decrypt_json(text)
    else:
        messages = parse_weflow_json(text)

    if not messages:
        raise ValueError("未能解析出消息，请检查 JSON 格式是否为 WeFlow 或微信解密导出。")
    return messages
